baseURL = "https://mreisgies.github.io/blog/"
languageCode = "en-us"
title = "Blog von Markus Reisgies"
theme = "hugo-profile"

[params]
  author = "Markus Reisgies"
  description = "Ein Blog von mir, um Dinge zu teilen."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/MReisgies"